name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # - name: Check PowerShell
      #   run: $PSVersionTable

      - name: Check repository
        uses: actions/checkout@v3

      # - name: Check Node.js version
      #   run: node -v

      - name: npm install
        working-directory: ./frontend
        run: npm i

      - name: npm build
        working-directory: ./frontend
        run: npm run build

      - name: nginx stert
        working-directory: ./frontend
        run: |
          docker rm -f web
          docker run -d -p 80:80 -v ./dist:/usr/share/nginx/html -v ./default.conf:/etc/nginx/conf.d/default.conf --name web nginx:1.28



