name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # - name: Check PowerShell
      #   run: $PSVersionTable
      - name: Check repository
        uses: actions/checkout@v3

      # - name: Check Node.js version
      #   run: node -v

      - name: npm install
        run: npm i

